In [5]:
import numpy as np
import pandas as pd

In [28]:
# class Y
Y = np.array([[1, 0, 0, 0],
              [1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1],
              [0, 0, 0, 1]])

In [25]:
np.shape(Y)

(8, 4)

In [11]:
X = np.array([[3,1,4],
              [4,5,7],
              [5,2,6],
              [6,3,8],
              [7,4,2],
              [8,2,1],
              [9,4,2],
              [10,2,3]])

In [12]:
np.shape(X)

(8, 3)

In [13]:
theta = np.array([[2, -0.1, 3, 1],
                  [-3, 0.2, 1, 1],
                  [3, 1, 0.01, -2]])

In [14]:
np.shape(theta)

(3, 4)

In [16]:
h = np.exp(X @ theta) / np.sum(np.exp(X @ theta))

In [17]:
h

array([[2.92342641e-08, 4.41797666e-13, 2.05017785e-10, 1.63793631e-16],
       [1.07546848e-08, 1.78695247e-11, 2.31676372e-07, 6.02563094e-17],
       [3.20592634e-05, 3.26446774e-12, 2.29371154e-07, 6.02563094e-17],
       [4.75801656e-03, 2.66581982e-11, 1.27762269e-05, 8.15480470e-18],
       [2.66581982e-11, 7.30286630e-14, 6.56935718e-04, 9.80700307e-12],
       [3.95642742e-09, 1.62948973e-14, 1.76796805e-03, 2.66581982e-11],
       [1.45548831e-09, 5.97908123e-14, 2.65026784e-01, 7.24644959e-11],
       [8.71461132e-05, 9.85783840e-14, 7.27657807e-01, 3.60779481e-12]])

In [18]:
np.shape(h)

(8, 4)

In [33]:
# find J(theta) which is loss
loss = - np.sum(Y * np.log(h))
loss

149.85339509068294

In [47]:
# get feature 2 of X
feature2 = X[:,1]
feature2

array([1, 5, 2, 3, 4, 2, 4, 2])

In [55]:
# feature2.T = arr??

array([1, 5, 2, 3, 4, 2, 4, 2])

In [57]:
np.shape(feature2.T)

(8,)

In [39]:
error = h - Y
error

array([[-9.99999971e-01,  4.41797666e-13,  2.05017785e-10,
         1.63793631e-16],
       [-9.99999989e-01,  1.78695247e-11,  2.31676372e-07,
         6.02563094e-17],
       [ 3.20592634e-05, -1.00000000e+00,  2.29371154e-07,
         6.02563094e-17],
       [ 4.75801656e-03, -1.00000000e+00,  1.27762269e-05,
         8.15480470e-18],
       [ 2.66581982e-11,  7.30286630e-14, -9.99343064e-01,
         9.80700307e-12],
       [ 3.95642742e-09,  1.62948973e-14, -9.98232032e-01,
         2.66581982e-11],
       [ 1.45548831e-09,  5.97908123e-14,  2.65026784e-01,
        -1.00000000e+00],
       [ 8.71461132e-05,  9.85783840e-14,  7.27657807e-01,
        -1.00000000e+00]])

In [49]:
np.shape(error)

(8, 4)

In [50]:
np.shape(feature2)

(8,)

In [58]:
gradient_feature2 = feature2 . T @ error
gradient_feature2

array([-5.98548744, -5.        , -3.47837362, -6.        ])

In [59]:
gradient = X.T @ error

In [60]:
gradient

array([[ -6.97041997, -11.        ,  -5.31935985, -19.        ],
       [ -5.98548744,  -5.        ,  -3.47837362,  -6.        ],
       [-10.96148187, -14.        ,  -0.28378596,  -5.        ]])

In [62]:
np.shape(gradient)

(3, 4)

K Nearest Neighbours

In [65]:
def find_distance(X_train, X_test):
    #create newaxis simply so that broadcast to all values
    dist = X_test[:, np.newaxis, :] - X_train[np.newaxis, :, :]
    sq_dist = dist ** 2
    
    #sum across feature dimension, thus axis = 2
    summed_dist = sq_dist.sum(axis=2)  #basically x + y
    sq_dist = np.sqrt(summed_dist)
    return sq_dist

In [63]:
train_ex = np.array([[1, 2], [2, 3]]) #(2, 2)
test_ex  = np.array([[3, 4]]) #(1, 2)

In [66]:
 d = find_distance(train_ex, test_ex)
print(d.shape)
d

(1, 2)


array([[2.82842712, 1.41421356]])

In [68]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Shuffle the rows
shuffled_array = np.random.permutation(array_2d)

print(shuffled_array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
